version: "3.5"
services:
  tecmapper:
    container_name: tecmapper
    build: .
    labels:
      com.centurylinklabs.watchtower.enable: false
    volumes:
      - ionex:/ionex
    restart: unless-stopped
    ports:
      - "5100:5100"
    command: bokeh serve /app --port 5100 --allow-websocket-origin="tec.jopppis.com" --args --cache_dir /ionex -v

volumes:
  ionex:
